<?php
// Path to JSON file generated by the Python script
$json_file_path = 'output.json';

// Read the JSON file
$json_data = file_get_contents($json_file_path);

// Decode JSON data into an associative array
$data = json_decode($json_data, true);

// Check if data is successfully parsed
if ($data === null) {
    die("Error decoding JSON data.");
}

// Display or manipulate the data as required
foreach ($data as $record) {
    echo "Timestamp: " . $record['ts'] . "\n";
    echo "Principal Component 1: " . $record['principal component 1'] . "\n";
    echo "Principal Component 2: " . $record['principal component 2'] . "\n";
    echo "\n";
}
?>
